# Generated by Django 4.0.5 on 2022-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='add_to_list',
            field=models.CharField(blank=True, choices=[('want to play', 'Want To Play'), ('currently playing', 'Currently Playing'), ('finished playing', 'Finished Playing'), ('stopped playing', 'Stopped Playing')], default='finished playing', max_length=17),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=110),
        ),
    ]
