# Generated by Django 4.0.5 on 2022-06-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_game_developer_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
