# Generated by Django 4.0.5 on 2022-06-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='add_to_list',
            field=models.CharField(blank=True, choices=[('want to play', 'Want To Play'), ('currently playing', 'Currently Playing'), ('finished playing', 'Finished Playing'), ('stopped playing', 'Stopped Playing')], default='finished playing', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_art',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=103, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=102, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
